language: go
go:
- 1.4
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/mitchellh/gox
- gox -build-toolchain -osarch=linux/386
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_script:
- goveralls -coverprofile=.profile.cov
after_success:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_7f4c34587607_key -iv $encrypted_7f4c34587607_iv -in tool/travis/autotag_deploy_key.enc -out ../deploy.key -d
- cp ../deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- git config --global user.email "mackerel-developers@hatena.ne.jp"
- git config --global user.name  "mackerel"
- git remote set-url origin git@github.com:mackerelio/mackerel-agent-plugins.git
- tool/autotag
deploy:
  provider: releases
  api_key:
    secure: c2pLKkM2leWMIzakVisNf3kAK6TBYslDM8SFEVrTTHpHnTI/6jUFnDLuL9cKuq9c76QcgYfqdLDn/hP+uFHf5WdtdJR00R+bX8cCx6NfOe7Kk9GlqGinUcXKAVs0kQHaYtQrN/rCOIG92kYFdbRHMD8uMrADJVRySePTMMhMX9o=
  file:
  - "/home/travis/rpmbuild/RPMS/noarch/mackerel-agent-plugins-0.15.1-1.noarch.rpm"
  - "/home/travis/gopath/src/github.com/mackerelio/mackerel-agent-plugins/packaging/mackerel-agent-plugins_0.15.1-1_all.deb"
  skip_cleanup: true
  on:
    repo: mackerelio/mackerel-agent-plugins
    all_branches: true
    tags: true
notifications:
  slack:
    secure: cPeJRg+ouTlemEV5UM4muhDwtIM0dktcs3mnfB73oZ2MGOimv/DFpL+VTRLlkWau8l0dT4ngLlGPcveLrXQXwps2LsJMr+gS6Az/CAQCIl21oj4bnjs5uGYTG8hM8ymVzGINPNnj5Fnn5DUMunA2sow30qxfuCnSUMGot2nFRKw=
